# multi-node cluster config - two workers
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 80
  - containerPort: 30306
    hostPort: 3307
  - containerPort: 30081
    hostPort: 8080
- role: worker
- role: worker
