apiVersion: v1
kind: Namespace
metadata:
  name: library-app
---
apiVersion: v1
kind: Service
metadata:
  name: library-app-service
  namespace: library-app
spec:
  type: NodePort
  selector:
    app: library
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30081